# First print your name in the cell below then save this file. (or something nice about your instructor)

In [1]:
# In this cell print your name 
print("abubakar")

abubakar

# Data wrangling with Pandas exercise
* For this exercise we will be using the `listings.csv` data file.

In [2]:
import pandas as pd
import numpy as np

# Load in the data file using `pd.read_csv()`

In [6]:
# Load data here
df = pd.read_csv('data/listings.csv')

## Exercise 2 - Filtering

Return the following subsets of the dataframe.

1. How many listings are there with a price less than 100? 


2. Find how many listings there are in just Brooklyn.


3. Find how many listings there are in Brooklyn with a price less than 100.


4. Using `.isin()` select anyone that has the host name of Michael, David, John, and Daniel.


5. Create a new column called `adjusted_price` that has $100 added to every listing in Williamsburg.  The prices for all other listings should be the same as the were before. 


6. What % of the rooms are private, and what % of the rooms are shared.  
    * Hint, use `.value_counts()`

In [7]:
# 1. How many listings are there with a price less than 100? 
df['price'] < 100

0        False
1         True
2         True
3        False
4         True
         ...
46522    False
46523     True
46524     True
46525     True
46526     True
Name: price, Length: 46527, dtype: bool

In [9]:
# 2. Make a new DataFrame of listings in Brooklyn named `df_bk` 
# and find how many listings in just Brooklyn.
# Make a new DataFrame with only Brooklyn listings
df_bk = df[df['neighbourhood_group'] == 'Brooklyn']

# Find how many listings are in Brooklyn
len(df_bk)

46527

In [10]:
# 3. Find how many listings there are in Brooklyn with a price less than 100.

len(df_bk[df_bk['price'] < 100])

22778

In [11]:
# 4. Using `.isin()` select anyone that has the host name of Michael, David, John, and Daniel.
# How many total are there that have those names

names = ['Michael', 'David', 'John', 'Daniel']

df_names = df[df['host_name'].isin(names)]

len(df_names)

1258

In [12]:
# 5. Create a new column called `adjusted_price` that has $100 added to every listing in Williamsburg.  
# The prices for all other listings should be the same as the were before. 
df["adjusted_price"] = df["price"]

# $100 listing to williamsburg column
df.loc[df['neighbourhood'] == 'Williamsburg', 'adjusted_price'] += 100

In [13]:
# 6. What % of the rooms are private, and what % of the rooms are shared.  
private_percent = (df['room_type'] == 'Private room').mean() * 100
shared_percent = (df['room_type'] == 'Shared room').mean() * 100

print("Private rooms:", private_percent, "%")
print("Shared rooms:", shared_percent, "%")

Private rooms: 45.444580566122895 %
Shared rooms: 2.12134889419047 %

# Exercise 3 - Grouping

1. Using `groupby`, count how many listings are in each neighbourhood_group.


2. Using `groupby`, find the mean price for each of the neighbourhood_groups. 


3. Using `groupby` and `.agg()`, find the min and max price for each of the neighbourhood_groups. 


4. Using `groupby`, find the median price for each room type in each neighbourhood_group.


5. Using `groupby` and `.agg()`, find the count, min, max, mean, median, and std of the prices for each room type in each neighbourhood_group.

In [15]:
# 1. Using `groupby`, count how many listings are in each neighbourhood_group.
df.groupby('neighbourhood_group').size()

neighbourhood_group
Brooklyn    46527
dtype: int64

In [16]:
# 2. Using `groupby`, find the mean price for each of the neighbourhood_groups. 

df.groupby('neighbourhood_group')['price'].mean()

neighbourhood_group
Brooklyn    148.60567
Name: price, dtype: float64

In [ ]:
# 2.5. Using `groupby`, find the mean price for each room_type. 
df.groupby('neighbourhood_group')['price'].mean()

In [17]:
# 3. Using `groupby` and `.agg()`, find the min and max price for each of the neighbourhood_groups. 

df.groupby('neighbourhood_group')['price'].agg(['min', 'max'])

                     min    max
neighbourhood_group
Brooklyn               0  10000

In [ ]:
# 4. Using `groupby`, find the mean price for each room_type in each neighbourhood_group.
df.groupby(['neighbourhood_group', 'room_type'])['price'].mean()

In [18]:
# 5. Using `groupby` and `.agg()`, find the count, min, max, mean, median, and std of the prices 
# for each room type in each neighbourhood_group.
df.groupby(['neighbourhood_group', 'room_type'])['price'].agg(
    ['count', 'min', 'max', 'mean', 'median', 'std']
)

                                     count  min    max        mean  median  \
neighbourhood_group room_type
Brooklyn            Entire home/apt  23998    0  10000  199.395950   150.0
                    Hotel room         398    0   2211  275.015075   192.0
                    Private room     21144   10  10000   91.453084    65.0
                    Shared room        987   10  10000   87.063830    46.0

                                            std
neighbourhood_group room_type
Brooklyn            Entire home/apt  337.657116
                    Hotel room       301.658021
                    Private room     282.450148
                    Shared room      354.048373

# Load, Merge, and Export files.
1. Load the `prices.csv` and the `n_listings.csv`
    * Having an error..? Inspect the actual csv file if you're having trouble

2. Do join that keeps all the records for each table.
    * Neighbourhood groups should include ['Bronx', 'Brooklyn', 'Manhattan', 'Queens', 'Staten Island',
       'LongIsland']

       
3. Save your joined csv as `joined.csv` into the data folder. 


4. Load your saved table and see if it looks the same or different that the DataFrame you used to create it.

In [20]:
# 1. Load the `prices.csv` and the `n_listings.csv`
import pandas as pd

# 1. Load both CSV files
prices = pd.read_csv('data/prices.csv')
n_listings = pd.read_csv('data/n_listings.csv')

# Check them
display(prices)
display(n_listings)

  neighbourhood_group   mean_price
0               Bronx    92.751479
1            Brooklyn   120.225258
2           Manhattan   191.880466
3              Queens    99.754965
4       Staten Island   110.947214

  neighbourhood_group;n_listings
0                     Bronx;1183
1                 Brooklyn;18632
2                Manhattan;20580
3                LongIsland;4121

In [28]:
# 2. Do join that keeps all the records for each table.
# 2. Keep all records from BOTH tables

In [ ]:
# 3. Save your joined csv as `joined.csv` into the data folder.

In [ ]:
# 4. Load your newly saved file, see if it looks the same.  If not, try saving with argument `index=False`

# Extra Credit
Every question below this cell is extra credit and optional.

### 2. (Very Easy) Find other cool Panda packages / add ons and show us what they can do well. And how you installed them.

### 3. (Medium) Use the grammys.csv data for the next section of questions.

1. Who was won Album of the Year in 2016?


2. Who won Best Rap Album in 2009?


3. How many awards was Kendrick Lamar nomiated for, and how many did he win...?

### (Hard) Load the Game Logs for 2022 and add the column names using a dictionary.  
* [Link to the data page](https://www.retrosheet.org/gamelogs/)
* [Link to the column names](https://procatinator.com/)
* haha, gotta find them yourself!

### (Extra Hard) Download the files for the past 5 years into a new folder and add them all into one data frame using pandas, then save that new file.
* Try to not hard code in the file names. We want to do this programmatically because what if we want to add new/more file names in the future.